language: node_js
node_js:
  - 4
  - 5
  - 6
  - node
git:
  depth: 3
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-4.8 -y
  - gcc --version
after_script:
  - npm run-script coveralls